[2023-12-30T17:54:02.602+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.get_data manual__2023-12-30T12:54:00.195552+00:00 [queued]>
[2023-12-30T17:54:02.657+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.get_data manual__2023-12-30T12:54:00.195552+00:00 [queued]>
[2023-12-30T17:54:02.657+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-30T17:54:02.680+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-30 12:54:00.195552+00:00
[2023-12-30T17:54:02.691+0500] {standard_task_runner.py:57} INFO - Started process 23366 to run task
[2023-12-30T17:54:02.701+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'get_data', 'manual__2023-12-30T12:54:00.195552+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmpor1i0q54']
[2023-12-30T17:54:02.703+0500] {standard_task_runner.py:85} INFO - Job 366: Subtask get_data
[2023-12-30T17:54:02.797+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.get_data manual__2023-12-30T12:54:00.195552+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-30T17:54:02.956+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T12:54:00.195552+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-30T12:54:00.195552+00:00'
[2023-12-30T17:54:02.957+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-30T17:54:02.958+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/datasets && gdown 1X-mGhWO8DwPLljP1e0gkdAloD-GL8SLq']
[2023-12-30T17:54:02.979+0500] {subprocess.py:86} INFO - Output:
[2023-12-30T17:54:05.224+0500] {subprocess.py:93} INFO - Downloading...
[2023-12-30T17:54:05.225+0500] {subprocess.py:93} INFO - From: https://drive.google.com/uc?id=1X-mGhWO8DwPLljP1e0gkdAloD-GL8SLq
[2023-12-30T17:54:05.225+0500] {subprocess.py:93} INFO - To: /home/kda/ML_lab3/MLops_lab3/datasets/Sport_car_price.csv
[2023-12-30T17:54:05.282+0500] {subprocess.py:93} INFO -   0%|          | 0.00/49.2k [00:00<?, ?B/s]100%|##########| 49.2k/49.2k [00:00<00:00, 3.21MB/s]
[2023-12-30T17:54:05.334+0500] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-30T17:54:05.376+0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=KOH, task_id=get_data, execution_date=20231230T125400, start_date=20231230T125402, end_date=20231230T125405
[2023-12-30T17:54:05.464+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-30T17:54:05.487+0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
