[2023-12-27T22:40:11.424+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-27T17:39:36.582967+00:00 [queued]>
[2023-12-27T22:40:11.429+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.evaluate manual__2023-12-27T17:39:36.582967+00:00 [queued]>
[2023-12-27T22:40:11.429+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-27T22:40:11.445+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): evaluate> on 2023-12-27 17:39:36.582967+00:00
[2023-12-27T22:40:11.450+0500] {standard_task_runner.py:57} INFO - Started process 5755 to run task
[2023-12-27T22:40:11.453+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'evaluate', 'manual__2023-12-27T17:39:36.582967+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmpd2ghw23_']
[2023-12-27T22:40:11.456+0500] {standard_task_runner.py:85} INFO - Job 171: Subtask evaluate
[2023-12-27T22:40:11.498+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.evaluate manual__2023-12-27T17:39:36.582967+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-27T22:40:11.565+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='evaluate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T17:39:36.582967+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-27T17:39:36.582967+00:00'
[2023-12-27T22:40:11.566+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-27T22:40:11.567+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/kda/ML_lab3/MLops_lab3/ && python /home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py']
[2023-12-27T22:40:11.573+0500] {subprocess.py:86} INFO - Output:
[2023-12-27T22:40:14.176+0500] {subprocess.py:93} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-12-27T22:40:14.177+0500] {subprocess.py:93} INFO - RangeIndex: 704 entries, 0 to 703
[2023-12-27T22:40:14.178+0500] {subprocess.py:93} INFO - Columns: 220 entries, Price (in USD) to i8
[2023-12-27T22:40:14.185+0500] {subprocess.py:93} INFO - dtypes: bool(212), float64(2), int64(6)
[2023-12-27T22:40:14.185+0500] {subprocess.py:93} INFO - memory usage: 189.9 KB
[2023-12-27T22:40:14.185+0500] {subprocess.py:93} INFO -      Price (in USD)  Unnamed: 0.2  Unnamed: 0.1  ...  Z4 M40i  Z4 Roadster     i8
[2023-12-27T22:40:14.185+0500] {subprocess.py:93} INFO - 0             67600           912           912  ...    False        False  False
[2023-12-27T22:40:14.185+0500] {subprocess.py:93} INFO - 1             81250           843           843  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 2             69000           293           293  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 3            180000           554           554  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 4             64695           581           581  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - ..              ...           ...           ...  ...      ...          ...    ...
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 298          250000           951           951  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 299         2600000           523           523  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 300          103500            61            61  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 301          157500           355           355  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 302          200000           335           335  ...    False        False  False
[2023-12-27T22:40:14.186+0500] {subprocess.py:93} INFO - 
[2023-12-27T22:40:14.187+0500] {subprocess.py:93} INFO - [303 rows x 220 columns]
[2023-12-27T22:40:14.187+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-27T22:40:14.188+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py", line 130, in <module>
[2023-12-27T22:40:14.188+0500] {subprocess.py:93} INFO -     tune_hyperparams(X_train,y_train,x_test,y_test)
[2023-12-27T22:40:14.188+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/evaluate.py", line 57, in tune_hyperparams
[2023-12-27T22:40:14.188+0500] {subprocess.py:93} INFO -     for params in search_space(*search_space.values()):
[2023-12-27T22:40:14.188+0500] {subprocess.py:93} INFO - TypeError: 'dict' object is not callable
[2023-12-27T22:40:14.586+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-27T22:40:14.600+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-27T22:40:14.611+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=KOH, task_id=evaluate, execution_date=20231227T173936, start_date=20231227T174011, end_date=20231227T174014
[2023-12-27T22:40:14.642+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 171 for task evaluate (Bash command failed. The command returned a non-zero exit code 1.; 5755)
[2023-12-27T22:40:14.650+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-27T22:40:14.663+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
