[2023-12-10T18:05:20.893+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: KOH.data_1 manual__2023-12-10T13:05:09.643652+00:00 [queued]>
[2023-12-10T18:05:20.906+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: KOH.data_1 manual__2023-12-10T13:05:09.643652+00:00 [queued]>
[2023-12-10T18:05:20.909+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-10T18:05:20.958+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_1> on 2023-12-10 13:05:09.643652+00:00
[2023-12-10T18:05:20.963+0500] {standard_task_runner.py:57} INFO - Started process 5541 to run task
[2023-12-10T18:05:20.968+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'KOH', 'data_1', 'manual__2023-12-10T13:05:09.643652+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/text.py', '--cfg-path', '/tmp/tmporr5umbs']
[2023-12-10T18:05:20.969+0500] {standard_task_runner.py:85} INFO - Job 14: Subtask data_1
[2023-12-10T18:05:21.120+0500] {task_command.py:416} INFO - Running <TaskInstance: KOH.data_1 manual__2023-12-10T13:05:09.643652+00:00 [running]> on host vm2.myguest.virtualbox.org
[2023-12-10T18:05:21.242+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Admin' AIRFLOW_CTX_DAG_ID='KOH' AIRFLOW_CTX_TASK_ID='data_1' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T13:05:09.643652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-10T13:05:09.643652+00:00'
[2023-12-10T18:05:21.246+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-10T18:05:21.249+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /home/kda/ML_lab3/MLops_lab3/scripts/script1.py']
[2023-12-10T18:05:21.262+0500] {subprocess.py:86} INFO - Output:
[2023-12-10T18:05:22.502+0500] {subprocess.py:93} INFO - Engine Size (L)
[2023-12-10T18:05:22.503+0500] {subprocess.py:93} INFO - Gas         974
[2023-12-10T18:05:22.503+0500] {subprocess.py:93} INFO - Electric     33
[2023-12-10T18:05:22.503+0500] {subprocess.py:93} INFO - Name: count, dtype: int64
[2023-12-10T18:05:22.503+0500] {subprocess.py:93} INFO - Car Make                   0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Car Model                  0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Year                       0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Engine Size (L)            0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Horsepower                 0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Torque (lb-ft)             3
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - 0-60 MPH Time (seconds)    0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - Price (in USD)             0
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO - dtype: int64
[2023-12-10T18:05:22.504+0500] {subprocess.py:93} INFO -      Car Make      Car Model  ...  0-60 MPH Time (seconds) Price (in USD)
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - 642     Tesla  Model S Plaid  ...                      1.9        139,990
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - 878  Maserati    GranTurismo  ...                      2.8        200,000
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - 916     Tesla       Roadster  ...                      1.9        200,000
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - 
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - [3 rows x 8 columns]
[2023-12-10T18:05:22.505+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-10T18:05:22.506+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/scripts/script1.py", line 27, in <module>
[2023-12-10T18:05:22.506+0500] {subprocess.py:93} INFO -     scp["Torque (lb-ft)"] = scp["Torque (lb-ft)"].astype(int)
[2023-12-10T18:05:22.506+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/generic.py", line 6534, in astype
[2023-12-10T18:05:22.513+0500] {subprocess.py:93} INFO -     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
[2023-12-10T18:05:22.515+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 414, in astype
[2023-12-10T18:05:22.518+0500] {subprocess.py:93} INFO -     return self.apply(
[2023-12-10T18:05:22.519+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 354, in apply
[2023-12-10T18:05:22.521+0500] {subprocess.py:93} INFO -     applied = getattr(b, f)(**kwargs)
[2023-12-10T18:05:22.522+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 616, in astype
[2023-12-10T18:05:22.524+0500] {subprocess.py:93} INFO -     new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
[2023-12-10T18:05:22.524+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 238, in astype_array_safe
[2023-12-10T18:05:22.532+0500] {subprocess.py:93} INFO -     new_values = astype_array(values, dtype, copy=copy)
[2023-12-10T18:05:22.532+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 183, in astype_array
[2023-12-10T18:05:22.532+0500] {subprocess.py:93} INFO -     values = _astype_nansafe(values, dtype, copy=copy)
[2023-12-10T18:05:22.532+0500] {subprocess.py:93} INFO -   File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 134, in _astype_nansafe
[2023-12-10T18:05:22.533+0500] {subprocess.py:93} INFO -     return arr.astype(dtype, copy=True)
[2023-12-10T18:05:22.533+0500] {subprocess.py:93} INFO - ValueError: invalid literal for int() with base 10: 'nan'
[2023-12-10T18:05:22.723+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-10T18:05:22.730+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kda/ML_lab3/MLops_lab3/lab3/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-10T18:05:22.733+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=KOH, task_id=data_1, execution_date=20231210T130509, start_date=20231210T130520, end_date=20231210T130522
[2023-12-10T18:05:22.768+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task data_1 (Bash command failed. The command returned a non-zero exit code 1.; 5541)
[2023-12-10T18:05:22.799+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-10T18:05:22.841+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
